name: deploy1.yml
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: corretto
      - name: Install Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Bump Version
        id: bump
        run: | 
          set -e 
          mvn -B -q build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
          VER="$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)"
          echo "NOVA VERSAO: $VER"
          echo "version=$VER" >> "$GITHUB_OUTPUT"
      - name: Build Project
        run: |
            mvn -B -q -DskipTests package
      - name: Copy Artefato
        run: | 
          cp target/*.jar docker/app.jar
      - name: Build Docker
        run: |
          cd docker
          VER=${{steps.bump.outputs.version}}
          echo "NOVA VERSAO $VER"
          docker build . -t cervejaria:${{steps.bump.outputs.version}}
          
