name: deploy1.yml
on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: self-hosted
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Java
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: corretto
      - name: Install Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: '3.8.2'
      - name: Bump Version
        id: bump
        run: | 
          set -e 
          mvn -B -q build-helper:parse-version versions:set -DnewVersion=\${parsedVersion.majorVersion}.\${parsedVersion.minorVersion}.\${parsedVersion.nextIncrementalVersion} versions:commit
          VER="$(mvn -q help:evaluate -Dexpression=project.version -DforceStdout)"
          echo "NOVA VERSAO: $VER"
          echo "version=$VER" >> "$GITHUB_OUTPUT"
      - name: Build Project
        run: |
            mvn -B -q -DskipTests package
      - name: Copy Artefato
        run: | 
          cp target/*.jar docker/app.jar
      - name: Build Docker
        run: |
          cd docker
          VER=${{steps.bump.outputs.version}}
          echo "NOVA VERSAO $VER"
          docker build . -t cervejaria:${{steps.bump.outputs.version}}
          
      - name: Docker TAG
        run: |
          docker tag cervejaria:${{steps.bump.outputs.version}} localhost:5001/cervejaria:${{steps.bump.outputs.version}}
          docker tag cervejaria:${{steps.bump.outputs.version}} localhost:5001/cervejaria:latest
      - name: Docker PUSH
        run: |
          docker push  localhost:5001/cervejaria:latest
          docker push  localhost:5001/cervejaria:${{steps.bump.outputs.version}}
      - name: Commit POM
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: 'github bot ci: BUMP para a versao ${{steps.bump.outputs.version}}'
          file_pattern: 'pom.xml'


      - name: Reiniciar Deployment
        run: |
          set -e 
          kubectl rollout restart deploy cervejaria-deploy -n cervejaria
      - name: Verificar Deploy
        run: |
          kubectl rollout status deploy cervejaria-deploy -n cervejaria --timeout=300s
